### ISSUE TITLE
run generate_pretrain_dataset.py, KeyError: 'homo'

### ISSUE THREAD

**Issue by AcaciaSin** [NYUSHCS/MolecularGPT#2]
File "/home/ztxian/MolecularGPT/prompts/generate_pretrain_dataset.py", line 149, in generate_assay_data
    text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
KeyError: 'homo'

When running the instructions "python generate_pretrain_dataset.py --generate_assay_text --generate_mole_text --generate_qm9_text --split_non_overlap --add_negation" for the first time, this error arised.

**Comment by Rirock** [comment]
Traceback (most recent call last):
  File "/mnt/f/codes/MolecularGPT/prompts/generate_pretrain_dataset.py", line 337, in <module>
    generate_assay_data(train_assays,set(train_graph_index),'train')
  File "/mnt/f/codes/MolecularGPT/prompts/generate_pretrain_dataset.py", line 141, in generate_assay_data
    text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
KeyError: 'homo'

I have the same problem, could you tell me how to solve it?

**Comment by zhoufy20** [comment]
> File "/home/ztxian/MolecularGPT/prompts/generate_pretrain_dataset.py", line 149, in generate_assay_data text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))] KeyError: 'homo'
> 
> When running the instructions "python generate_pretrain_dataset.py --generate_assay_text --generate_mole_text --generate_qm9_text --split_non_overlap --add_negation" for the first time, this error arised.

Can u tell me how to solve this problem? Thanks a lot!

**Comment by AcaciaSin** [comment]
> Traceback (most recent call last): File "/mnt/f/codes/MolecularGPT/prompts/generate_pretrain_dataset.py", line 337, in generate_assay_data(train_assays,set(train_graph_index),'train') File "/mnt/f/codes/MolecularGPT/prompts/generate_pretrain_dataset.py", line 141, in generate_assay_data text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))] KeyError: 'homo'
> 
> I have the same problem, could you tell me how to solve it?

Have you successfully downloaded the qm9 dataset?

**Comment by zhoufy20** [comment]
```bash
Traceback (most recent call last):
  File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 377, in <module>
    generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
  File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 162, in generate_assay_data
    text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
KeyError: 'homo'
```

Upon reviewing the code, I suspect that the issue stems from the absence of a homo key within prompts['chembl'] as referenced in the `generate_pretrain_dataset.py` script on GitHub: https://github.com/NYUSHCS/MolecularGPT/blob/main/prompts/generate_pretrain_dataset.py#L141. The prompts = commentjson.load('prompt_pretrain.json'), maybe have nothing with qm9 dataset, and I cannot search `homo` in  'prompt_pretrain.json'.

**Comment by AcaciaSin** [comment]
> ```shell
> Traceback (most recent call last):
>   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 377, in <module>
>     generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
>   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 162, in generate_assay_data
>     text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
> KeyError: 'homo'
> ```
> 
> Upon reviewing the code, I suspect that the issue stems from the absence of a homo key within prompts['chembl'] as referenced in the `generate_pretrain_dataset.py` script on GitHub: https://github.com/NYUSHCS/MolecularGPT/blob/main/prompts/generate_pretrain_dataset.py#L141.
> 
> The prompts = commentjson.load('prompt_pretrain.json'), maybe have nothing with qm9 dataset, and I cannot search `homo` in 'prompt_pretrain.json'.

'homo' is a molecular property in the qm9 dataset, and if you haven't downloaded the dataset, you can skip some of the code that processing the qm9 dataset.

**Comment by zhoufy20** [comment]
> omo' is a molecular property in the qm9 dataset, and if you haven't downloaded the dataset, you can skip some of the code that processing the qm9 dataset.

Thanks a lot @AcaciaSin , whether `chembl` or `qm`, they both execute `load_split_file` in `generate_pretrain_dataset.py`, at this time, the error above occurs. Because there is no `homo` in `chembl`, but `chembl` use it.

**Comment by zhoufy20** [comment]
> > ```shell
> > Traceback (most recent call last):
> >   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 377, in <module>
> >     generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
> >   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 162, in generate_assay_data
> >     text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
> > KeyError: 'homo'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Upon reviewing the code, I suspect that the issue stems from the absence of a homo key within prompts['chembl'] as referenced in the `generate_pretrain_dataset.py` script on GitHub: https://github.com/NYUSHCS/MolecularGPT/blob/main/prompts/generate_pretrain_dataset.py#L141.
> > The prompts = commentjson.load('prompt_pretrain.json'), maybe have nothing with qm9 dataset, and I cannot search `homo` in 'prompt_pretrain.json'.
> 
> 'homo' is a molecular property in the qm9 dataset, and if you haven't downloaded the dataset, you can skip some of the code that processing the qm9 dataset.

Thanks a lot @AcaciaSin, but for `chembl` dataset ,we prepare this code 
```
    else:
        print('Warning! Creating new split')
    
        train_assays = ['homo','lumo'] # Highest Occupied Molecular Orbital energy & Lowest Unoccupied Molecular Orbital energy
        valid_assays = ['gap'] # homo-lumo

        if args.split_non_overlap:
            train_graph_index = np.random.choice(np.arange(133885), size=int(133885 * 0.8),
                                                 replace=False)
            valid_graph_index = np.delete(np.arange(133885), train_graph_index)
        else:
            train_graph_index = np.arange(133885)
            valid_graph_index = np.arange(133885)

        train_graph_index = train_graph_index.tolist()
        valid_graph_index = valid_graph_index.tolist()
        # `split_index` is a dict, stores every index and assay
        split_index = {}
        split_index['train_assays'] = train_assays
        split_index['valid_assays'] = valid_assays
        split_index['train_graph_index'] = train_graph_index
        split_index['valid_graph_index'] = valid_graph_index
        os.mkdir(split_file_dir)
        for key in split_index:
            df = pd.DataFrame(split_index[key], columns=['values'])
            df.to_csv(os.path.join(split_file_dir, key + '.csv'))
```
It means `train_assays = ['homo','lumo']`, and has been writen to `train_assays`. **How can it find `home` in it?**
```
        generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
        generate_assay_data(valid_assays,set(valid_graph_index),'valid') # valid_assays:['gap']
```
```
def generate_assay_data(assay_ids, molecule_index_set, split_name):
    # assay_ids（实验ID列表）、molecule_index_set（分子索引集合）和 split_name（分割名称）
    data_all = []
    for _, assay_chembl_id in tqdm(enumerate(assay_ids)):

        if args.augmented_type is not None:
            # 从列表中随机选择一个文本数据。
            type = args.augmented_type
            text_data = prompts_augmented['chembl'][assay_chembl_id][type][
                np.random.randint(len(prompts_augmented['chembl'][assay_chembl_id][type]))]
        else:
            text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
```

**Comment by gjk753** [comment]
不知道你们是否解决这个问题，如果已经解决，希望能告知一下，谢谢。我正常的下载qm9.csv，也出现这样的错误。我检查代码和数据，发现是prompts['chembl']没有这个homo这个键

**Comment by gjk753** [comment]
> > > ```shell
> > > Traceback (most recent call last):
> > >   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 377, in <module>
> > >     generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
> > >   File "MolecularGPT/MolecularGPT-main/prompts/generate_pretrain_dataset.py", line 162, in generate_assay_data
> > >     text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
> > > KeyError: 'homo'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在查看代码时，我怀疑问题源于 github 上的脚本 https://github.com/NYUSHCS/MolecularGPT/blob/main/prompts/generate_pretrain_dataset.py#L141 中引用的 prompts['chembl'] 中缺少同键。提示 = commentjson.load（'prompt_pretrain.json'），可能与 qm9 数据集无关，我无法在 'prompt_pretrain.json' 中搜索。`generate_pretrain_dataset.py``homo`
> > 
> > 
> > 'homo' 是 QM9 数据集中的一个分子属性，如果你还没有下载数据集，你可以跳过一些处理 QM9 数据集的代码。
> 
> 非常感谢，但是对于数据集，我们准备了这段代码`chembl`
> 
> ```
>     else:
>         print('Warning! Creating new split')
>     
>         train_assays = ['homo','lumo'] # Highest Occupied Molecular Orbital energy & Lowest Unoccupied Molecular Orbital energy
>         valid_assays = ['gap'] # homo-lumo
> 
>         if args.split_non_overlap:
>             train_graph_index = np.random.choice(np.arange(133885), size=int(133885 * 0.8),
>                                                  replace=False)
>             valid_graph_index = np.delete(np.arange(133885), train_graph_index)
>         else:
>             train_graph_index = np.arange(133885)
>             valid_graph_index = np.arange(133885)
> 
>         train_graph_index = train_graph_index.tolist()
>         valid_graph_index = valid_graph_index.tolist()
>         # `split_index` is a dict, stores every index and assay
>         split_index = {}
>         split_index['train_assays'] = train_assays
>         split_index['valid_assays'] = valid_assays
>         split_index['train_graph_index'] = train_graph_index
>         split_index['valid_graph_index'] = valid_graph_index
>         os.mkdir(split_file_dir)
>         for key in split_index:
>             df = pd.DataFrame(split_index[key], columns=['values'])
>             df.to_csv(os.path.join(split_file_dir, key + '.csv'))
> ```
> 
> 它的意思是 ，并且已被写入 。**它是如何在其中找到的？**`train_assays = ['homo','lumo']``train_assays`
> 
> ```
>         generate_assay_data(train_assays,set(train_graph_index),'train') # train_assays:['homo', 'lumo']
>         generate_assay_data(valid_assays,set(valid_graph_index),'valid') # valid_assays:['gap']
> ```
> 
> ```
> def generate_assay_data(assay_ids, molecule_index_set, split_name):
>     # assay_ids（实验ID列表）、molecule_index_set（分子索引集合）和 split_name（分割名称）
>     data_all = []
>     for _, assay_chembl_id in tqdm(enumerate(assay_ids)):
> 
>         if args.augmented_type is not None:
>             # 从列表中随机选择一个文本数据。
>             type = args.augmented_type
>             text_data = prompts_augmented['chembl'][assay_chembl_id][type][
>                 np.random.randint(len(prompts_augmented['chembl'][assay_chembl_id][type]))]
>         else:
>             text_data = prompts['chembl'][assay_chembl_id][np.random.randint(len(prompts['chembl'][assay_chembl_id]))]
> ```

我正常的下载qm9.csv，也出现这样的错误。我检查代码和数据，发现是prompts['chembl']没有这个homo这个键，按照作者代码所展示的，他应该想获得的是类似chemlxxxx的数据，所以可能他这里传入的train_assays是错误的，这仅仅是我的猜想
